print("welcome to the interactive personal data collector!",end='\n\n')
name=str(input("please enter your name:"))
age=int(input("please enter your age:"))
height=float(input("please enter your height in meter:"))
favourite_number=int(input("please enter your favourite number:"))
birth_year = 2025 - age
print("")
print("Thank you! here is the information we collected:",end='\n\n')
print("name:",name,"(type:",type(name),", memory address:",id(name),")")
print("age:",age,"(type:",type(age),", memory address:",id(age),")")
print("height:",height,"(type:",type(height),", memory address:",id(height),")")
print("favourite_number:",favourite_number,"(type:",type(favourite_number),", memory address:",id(favourite_number),")")
print("")
print("your birth year is approximately :",birth_year,"(based on your age of",age,")")
print("")
print("Thank you for using personsal data collector. Goodbye!")
